# Generated by Django 5.2.4 on 2025-07-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contactus_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
