# Generated by Django 5.2.4 on 2025-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
