# Generated by Django 5.2.4 on 2025-07-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_userfeedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
