# Generated by Django 5.2.4 on 2025-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('protein', 'Protein Powder'), ('creatine', 'Creatine'), ('preworkout', 'Pre Workout'), ('bcaa', 'BCAA')], default='protein', max_length=50),
        ),
    ]
