# Generated by Django 5.2.4 on 2025-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.TextField(default='Your Address'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='full_name',
            field=models.CharField(default='Your Full Name', max_length=150),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.CharField(default='Ex.9090909090', max_length=20),
        ),
    ]
